### PR TITLE
Readme Changes

### LINKED ISSUE #8: broken link
heya!
in step 5 of "what to do" the link to the XHR md file is broken

### LINKED ISSUE #9: change git clone link to https
we had issues in the first week with people not being able to clone using the ssh link:
`git@github.com:lucymonie/api-workshop.git`

but 

`https://github.com/lucymonie/api-workshop.git`

would work

### PR DESCRIPTION
**Pull request by Jbarget**
- fixes #8 typo in link to xhr markdown file
- fixes #9 changes git clone instructions to use https instead of ssh

### CODE REVIEW

**Comment by lucymonie** [comment]
The only issue with the change to the git clone instruction is that (I believe) London folks are using SSH so this is contradictory info. Would it be better just to tell them to clone it without the terminal command? Otherwise, all good

**Comment by Jbarget** [comment]
maybe we can be explicit:

if you have ssh keys for github setup: {ssh link}
otherwise use: {https link}

**Comment by Jbarget** [comment]
@lucymonie what you thinking re https v ssh?

**Comment by lucymonie** [comment]
I've already fixed it.

**Comment by Jbarget** [comment]
lols sorry

**Pull request merged**
